version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.0-25.1
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_URLS: ldap:/// ldaps:///
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
  mariadb:
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    command:
      - "--character-set-server=latin1"
      - "--collation-server=latin1_swedish_ci"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/mysql:/var/lib/mysql
  keycloak:
    image: dcm4che/keycloak:16.1.1
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
      - "7600:7600"
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      LDAP_URL: ldaps://ldap:636
      KEYCLOAK_WAIT_FOR: ldap:636 mariadb:3306
      DB_VENDOR: mariadb
      KEYCLOAK_DB_CONNECTION_URL: jdbc:mariadb://mariadb:3306/keycloak
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
